### ISSUE TITLE
Request for clickable HTML

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Wil-YAT#1]
I would request you to give some clickable HTML file so that the user can click and check the image.
Something similar to fuzzyalpha.txt and fuzzyalpha.html would be welcome.

In my opinion, for correction the priority would be
1. ~= cases.
2. =vb cases.

The rest are mostly no change in my opinion.

**Comment by gasyoun** [comment]
Hope Jim understood 1,2 - I did not.

**Comment by gasyoun** [comment]
@funderburkjim did you?

**Comment by funderburkjim** [comment]
JIm has punted (not done).

If this is something someone is interested in working on, please refresh my memory on what needs to
be done to make the work more efficient.

**Comment by gasyoun** [comment]
Let @drdhaval2785 decide, to close or continue.

**Comment by drdhaval2785** [comment]
I prefer to close.
