### ISSUE TITLE
Oddities in Yates 'IAST'

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Wil-YAT#2]
In converting AS to modern IAST for Yates,  most is straightforward.
The text shows long vowels  as vowels-with-accents in place of the modern vowel+macron.
Vowels 'e' and 'o' are also shown with acute accent, whereas modern convention uses no diacritic.
And there are a small number of cerebral consonants represented by the modern convention of 
consonant+underdot.

All these are straightforward to understand.

However, there are numerous other odd aspects of the spelling of Sanskrit words in Latin alphabet.

For examples:
* Use of 'w' in place of 'v':   Aswamedha
* Inconsistency in representation of sibilants:  A**s**wamedha,  A**sh**wini4
* Absence of diacritics in common names: Vishnu,  Krishna

To be most useful to modern readers, it would be ideal to 'correct' these spellings to modern standards.

> Do others agree with this opinion?

This would be a substantial side-issue which I don't want to pursue at this time.

However, for the right person, identifying the Sanskrit words with Latin spelling, and bringing the spellings into modern form (consistent with headword spellings) might be an interesting task. 

If anyone has an interest in such a task, Iet me know -- I could help develop programs and documents
to facilitate the completion of the task.

**Comment by drdhaval2785** [comment]
IAST done.
