### ISSUE TITLE
Oddities in Yates Devanagari markup

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Wil-YAT#3]
### Two varieties of 'dot' in Devanagari
In the printed text, the Yates dictionary uses a 'dot' within Devanagari to indicate compound composition.

In the Cologne digitization,  this 'dot' is coded in either as
* a period character  (22000+ headword key2 instances)
* a backslash character (5000+ key2 instances).

**Comment by funderburkjim** [comment]
### Suggest 'period' be changed to '-'
The period character coding indicates where two compound words are joined, and usually where
the joining involves no sandhi.
* a.kzoBa  (a-kzoBa)  without shakiness
   ![image](https://cloud.githubusercontent.com/assets/6393033/26610002/e1736f0e-4572-11e7-8aac-539af3e41016.png)
* agni.kfta  (agni-kfta)  made by fire
   ![image](https://cloud.githubusercontent.com/assets/6393033/26610035/1f1a77e4-4573-11e7-9faf-431561923bc7.png)

While we're making some IAST and meta-line changes to Yates, I think we should
change these periods in key2 to hyphens.  Reason: the hyphen is used by MW in much the same way this period is used by Yates.  However, in MW and other European dictionaries, this markup is done for the IAST spelling of the word -- Yates seems unique in putting such markup in the Devanagari headword entry.

Do others agree to change this period to hyphen?

**Comment by funderburkjim** [comment]
### backslash for dot usu. means vowel sandhi 

There is a visible difference in the printed placement of the Yates dot, for those which the digitization codes with a backslash.  The general distinction appears to be that in such cases, the Yates dot is placed definitely UNDER a devagari letter (usually a vowel), rather than between two devanagari letters.

* agA\tmajA  (aga + AtmajA)
   ![image](https://cloud.githubusercontent.com/assets/6393033/26610442/7c443f70-4575-11e7-883a-fc565aa49a1c.png)
* malinA\mbu  (malina + ambu)
   ![image](https://cloud.githubusercontent.com/assets/6393033/26610555/3870682c-4576-11e7-893b-78237997865d.png)

In MW, these examples are rendered (in IAST) with a circumflex over an 'a', which is MW's way of indicating a long vowel resulting from simple vowel sandhi  (a + A -> A in the agAtmajA case); and
the digitization of mw (mw.xml) represents this with a special empty xml tag `<srs/>`  (simple-replacement-sandhi I think is the acronym Peter came up with).  (`agA<srs/>tmajA`).

![image](https://cloud.githubusercontent.com/assets/6393033/26610641/d7bd26c2-4576-11e7-9291-a95f8306187e.png)

#### Why backslash is poor choice

This is a technical reason:  we represent Devanagari with the SLP1 transliteration; and in the SLP1 transliteration, a vowel+backslash indicates an accent (anudAtta, in particular).   (/ = udAtta, ^ = svarita).

#### Maybe use underscore `_`  in place of backslash?

I don't think `_` has any meaning in SLP1 (no example comes to mind).  So SLP1 is neutral on this; and
also, in yat.txt,  there is currently no instance of `_`.

We could, in the conversion to yat.xml, convert this `_` to the MW convention `<srs/>` or just leave it as underscore; and we could choose in displays to either ignore it or display it in some way - probably ignore it since there is no generally accepted way to display it.  The Cologne MW displays use an 'asterisk' character to display `<srs/>`, but this is ugly, and certainly not intuitive.

**Comment by funderburkjim** [comment]
Any opinions of these two arcane minutiae ?

**Comment by drdhaval2785** [comment]
>Suggest 'period' be changed to '-'

I agree.

**Comment by drdhaval2785** [comment]
>Maybe use underscore _ in place of backslash?

Agree.

**Comment by gasyoun** [comment]
> hyphen is used by MW in much the same way this period is used by Yates

Agree.

> Yates dot is placed definitely UNDER a devagari letter

I thought Hertel invented the method in his HOS Panchatantra edition, but it was Yates 100 years before. Adore the method.

> simple-replacement-sandhi

Oh, that's how to read it...

> The Cologne MW displays use an 'asterisk' character to display <srs/>, but this is ugly, and certainly not intuitive.

Indeed.

**Comment by funderburkjim** [comment]
Have replaced the dots by hyphen and underscore, as described above.

**Comment by gasyoun** [comment]
> Have replaced the dots by hyphen and underscore

And added a link to this issue inside the download folder readme, right? Changes need to be documented not only on the web, but a meta-list should be there as well. We tend to forget ourselves. Others are not even aware of most and can get into confusion.

**Comment by funderburkjim** [comment]
> added a link to this issue

Mentioned it in [yat-meta2](http://sanskrit-lexicon.uni-koeln.de/scans/YATScan/2014/pywork/yat-meta2.txt).

Perhaps we should consider using the wiki feature of Github for such semi-permanent information about the dictionaries.  e.g., in the [Cologne repository wiki](https://github.com/sanskrit-lexicon/Cologne/wiki)

**Comment by gasyoun** [comment]
> Perhaps we should consider using the wiki feature of Github for such semi-permanent information about the dictionaries

Was thinking about a wider use of the wiki, exactly. Even I do not know what .txt should one read to understand how things are built. So much time is spent in documentation and it still remains for 5-10 people at best.
