### ISSUE TITLE
Wilson IAST

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Wil-YAT#4]
This issue discusses the conversion of the Wilson digitization to modern IAST.
I began this a week ago, and the task became much more complicated than expected.  Thus far, about 1700 changes have been made to the digitization, and the task is not yet complete.

### The scope of the problem
The way in which non-devanagari Sanskrit and other Indian language words are represented in Wilson is quite different than in other later nineteenth century European Sanskrit dictionaries.  The predominant diacritic mark is an acute accent. Over a vowel, the accent indicates a long vowel.  Over a consonant, the accent indicates some variant of the basic consonant; e.g., n+accent usually means retroflex nasal;  but this can represent a palatal or guttural nasal.  (In our particular digitization, accents may be represented by either a letter '4' with vowels  (a4 = long a) or with a single quote ( a' = long a).  Sometimes the vocalic 'r' is represented as `ri` and sometimes the 'i' has a breve: `rĭ``.

In addition to this confusing system, there are other spelling conventions: s' is palatal sibilant, sh is retroflex sibilant;  'w' is often used in place of 'v'; and there are other oddities.

And even these conventions are not used consistently. 
 For instance, we see KRISHNA and KRĬSHN'A;  here are all the ways this name appears in the digitization:
```
31 KRI12SHNA
1 KRI12SHN'A4
1 KRI4SHN'A
1 Krishn'a'
23 KRISHN'A
167 KRI12SHN'A
2 KRI10SHN'A
6 KRI12SHNA4
1 KRI12SH'NA
3 KRI12SHNA'S
8 KRI12SHN'A'S
1 KRI12SHN'AS
2 KRISHNA'S
1 Krishn'as
1 Kri12shn'as
1 KRI12SHNAS
```

### guiding principle of this conversion
There should be just one modern spelling:  ` KṚṢṆA`   All the variant forms should resolve (except for capitalization differences) to this one standard form.  

While we could have just dumbly converted all the forms to an IAST form while leaving the variations present in the printed text,  this seemed to me to be of much lesser utility than the approach taken.  I have not taken the trouble to identify as 'print changes' all the places where this conversion actively differs from the printed text.   For example, when both KRISHNA and KRĬSHN'A are converted to KṚṢṆA, no attempt has been made to identify whether either or both of these should be counted as print changes.  

There a few other points to mention - this will be done in subsequent comments.

**Comment by gasyoun** [comment]
> For instance, we see KRISHNA and KRĬSHN'A; here are all the ways this name appears in the digitization:

16 forms is 15 form more than needed, agree.

**Comment by funderburkjim** [comment]
The conversion of wil.txt to modern IAST now finished.  
Below are a few comments on methodology.

### Three steps
* words with a number or an apostrophe.
  As the example above shows,  both apostrophes and numbers were used in the digitization to
  represent Latin alphabet diacritics.  The first step was to deal with all words with such spellings.  Since
  the apostrophe also has use in English possessives, this case had to be weeded out.
* words with all capital letters
  Wilson often represents proper names with all capital letters, like KRISHNA.  On the one hand,  we 
  could decide to leave these spellings unchanged -- after all, there are no diacritics in the printed text.
  However, it was felt that the dictionary would be more useful if such all-cap words - *when they represented Sanskrit words * (like KRISHNA) - should also be converted to IAST.  Thus, it was also necessary to distinguish between all-cap Sanskrit and all-cap non-Sanskrit words.  For instance the author WILFORD appears several times in all caps, but the initial 'W' should not be changed to 'V' since this is a non-Sanskrit word.  There are on the order of 300 distinct all-cap words.
* Additional words without Diacritics.   By similar reasoning, these words need to be classified as Sanskrit or non-Sanskrit, and the spelling converted to modern IAST for those that are classified as Sanskrit.
This is a much larger class of words (approximately 27000 distinct spellings), and includes mostly English words, but also numerous Latin-derived words and non-Sanskrit Indian language words.

### Sanskrit or non-Sanskrit techniques
  In all three cases mentioned above, each word in the collection was identified as either Sanskrit or non-Sanskrit.   Several techniques were used in making the distinction.
* **MW or WIL headword**
   The IAST spelling of a word was computed, and then converted to SLP1 spelling.  If the resulting
   spelling appeared as a headword of Wilson or Monier-Williams, then the word was generally classified
   as Sanskrit.  Sometimes the IAST form might include an English plural or possessive ending; 
   `s` or `'s`, and if the word without this ending was Sanskrit, then the word was considered Sanskrit.
   Also, in a few (maybe 200) cases, the word was an inflected form  of a headword (e.g., `sannyAsI` for 
  `sannyAsin`) or was a compound of Sanskrit words.  These were also considered as Sanskrit words 
   and converted to modern IAST spelling.
* **context**
Many cases of plant or animal names (both Latinate forms and 'common' Indian language forms) can be readily identified by the context.  For questionable Indian language common names, reference to MW was also used.  Sometimes it was hard to distinguish whether a word (especially  a short word, like 'San')
was a Sanskrit word (SLP1 SaRa) or a common modern Indian Language word).  
*  **enchant** English
  In the last category (words with no diacritics and with not all caps), the most common classification was
  English words.  The Python interface Pyenchant to the Enchant English dictionaries was used.  This identified about 21000 out of 26000 words as being English.  One nice aspect of this system is that English inflections (like plurals, past tense, etc) are taken into account.
* specialized spelling features.
  Many of the Latin words (plant Linnaean classifications) could be identified by peculiarites of Latin spellings, such as :  ending in 'us', 'um',  containing consecutive vowels.   Many Indian place names (cities) ending in 'pur', and these were generally (but not always) considered non-Sanskrit. There were also some patterns
in Wilson (like `commonly {%X Y%}`) used with plant, animal scientific names.   Words gathered by such special filters amounted to maybe 1000 at most -- but every little bit helped.
* **other**
  Other generally means conferring with MW, or doing Google searches.  This was useful in identifying place names, archaic English words, Indian units of measure, plant or tree names, etc., etc.

### Utility for similar word classification in other dictionaries.
For various reasons, it might be useful to identify via markup the IAST Sanskrit words.   I have not done such markup here, but it would be possible to do so once a satisfactory markup scheme is devised.
Alternately, in developing an ElasticSearch full text search system (which may sometime be a successor to the current Advanced Search system),  this word classification could be made use of.

A more immediate use would be to take these word classifications into account when deciding how to
do IAST coding of Sanskrit words in other dictionaries (I'm thinking particularly of SHS).

**Comment by gasyoun** [comment]
> WILFORD appears several times in all caps, but the initial 'W' should not be changed to 'V' since this is a non-Sanskrit word

Seems you had interesting two weeks.

> was a Sanskrit word (SLP1 SaRa) or a common modern Indian Language word

And you did not share the fun with others, so greedy.

> Pyenchant to the Enchant English dictionaries was used

Too bad nobody will know how exactly. Or just running the general script worked? Guess not.

> more immediate use would be to take these word classifications into account when deciding how to
do IAST coding of Sanskrit words in other dictionaries (I'm thinking particularly of SHS).

Hope only after Simple Search is live and running. Seems to be a troublesome task.

**Comment by drdhaval2785** [comment]
IAST done for all dictionaries. Closing.

**Comment by gasyoun** [comment]
@funderburkjim  `elasticsearch` used lately for a Russian buddhist dictionary project https://github.com/dhilt/dharmadict
